apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cert-manager
name: cert-manager
namespace: cert-manager
version: 1.16.0
repo: https://charts.jetstack.io
releaseName: tkgt
includeCRDs: true
extraArgs:
  - "--install-crds"
valuesInline:
  global:
    leaderElection:
      namespace: cert-manager
