apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/esfelix/terra-k8s-gcp-test.git
    targetRevision: HEAD
    path: k8s/overlays/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
