apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 
    targetRevision: feature/to-1.27
    path: k8s/overlays/cluster/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
