apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./vendor-manifests/cert-manager-crds.yaml
  - ./vendor-manifests/cert-manager

patches:
  - target:
      group: "apps"
      version: v1
      kind: Deployment
      name: tkgt-cert-manager-webhook
      namespace: cert-manager
    path: patch-json6902-deployment.yaml
